workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "ppwee22@naver.com" 
    signing:
      app_store_connect:
        apple_id: "ppwee22@naver.com"
        password: "Changhwanlee"

        
